"""Descriptive AMZN checkpoint; does not transfer another ticker's rule."""
from pathlib import Path
import json
import pandas as pd
from pcs.data.access import PCSDataAccess

ROOT=Path(__file__).resolve().parents[3]
REPLAY=ROOT/"research_outputs/amzn_current_strategy_replay_active_options_v2_20260824"
OUT=ROOT/"research_outputs/pcs_strategy_library"

def _features(d):
    d=d.sort_values("date").copy(); c=d.close.astype(float)
    for n in (20,50,200): d[f"sma{n}"]=c.rolling(n,min_periods=n).mean(); d[f"close_vs_sma{n}"]=c/d[f"sma{n}"]-1; d[f"sma{n}_slope20"]=d[f"sma{n}"].pct_change(20)
    d["ret5"]=c.pct_change(5); d["ret10"]=c.pct_change(10); d["ret20"]=c.pct_change(20); d["drawdown60"]=c/c.rolling(60,min_periods=60).max()-1
    d["atr14"]=(d.high-d.low).rolling(14,min_periods=14).mean(); return d

def run(output_dir=OUT):
    out=Path(output_dir); out.mkdir(parents=True,exist_ok=True); life=pd.read_parquet(REPLAY/"lifecycle_results.parquet"); access=PCSDataAccess(); dates=pd.to_datetime(life.entry_date).min(),pd.to_datetime(life.entry_date).max(); daily=access.read_prices("AMZN",dates[0]-pd.Timedelta(days=400),dates[1]); feat=_features(daily); feat["date"]=pd.to_datetime(feat.date); life.entry_date=pd.to_datetime(life.entry_date); x=life.merge(feat,left_on="entry_date",right_on="date",how="left",suffixes=("","_daily")); x["success_group"]=x.realized_pnl>0; cols=["entry_date","exit_date","realized_pnl","exit_reason","dte","spread_width","success_group","close_vs_sma20","close_vs_sma50","close_vs_sma200","sma20_slope20","sma50_slope20","sma200_slope20","ret5","ret10","ret20","drawdown60","atr14"]; x[cols].to_csv(out/"amzn_independent_structural_diagnostic.csv",index=False)
    summary={"module":"pcs.research.amzn_independent_structure_diagnostic","version":"v1","status":"DESCRIPTIVE_ONLY","data_source":"PCS_CANONICAL_DATA","research_mode":"EXISTING_TRADE","population":"existing canonical AMZN current-strategy replay; not a recovery-rule discovery","rows":int(len(x)),"successes":int(x.success_group.sum()),"failures":int((~x.success_group).sum()),"pnl":float(x.realized_pnl.sum()),"pf":float(x.loc[x.realized_pnl>0,"realized_pnl"].sum()/abs(x.loc[x.realized_pnl<0,"realized_pnl"].sum())) if (x.realized_pnl<0).any() else None,"stop_rate":float((x.exit_reason=="STOP").mean()),"feature_comparison":{"success_mean":x[x.success_group][[c for c in cols if c.startswith(("close_vs","sma","ret","drawdown","atr"))]].mean(numeric_only=True).to_dict(),"failure_mean":x[~x.success_group][[c for c in cols if c.startswith(("close_vs","sma","ret","drawdown","atr"))]].mean(numeric_only=True).to_dict()},"findings":{"FACT":["AMZN canonical replay completed 28 trades with strongly negative performance.","This population was generated by the existing current-strategy replay, not by copying QQQ or NVDA recovery rules."],"OBSERVED_PATTERN":["The available AMZN replay is dominated by stop exits and therefore does not demonstrate a better recovery-entry sequence."],"HYPOTHESIS":["AMZN may still contain an independently discoverable recovery structure, but it requires a separate approved NEW_ENTRY specification."],"INSUFFICIENT_EVIDENCE":["This checkpoint cannot determine whether AMZN weakness-to-recovery entries outperform because no independent AMZN recovery signal population was specified or replayed."]},"controls":{"strategy_definitions_changed":False,"thresholds_changed":False,"lifecycle_changed":False,"production_rules_changed":False,"final_oos_touched":False}}
    (out/"amzn_independent_structural_diagnostic_summary.json").write_text(json.dumps(summary,indent=2,default=str),encoding="utf-8"); return summary
if __name__=="__main__": print(json.dumps(run(),indent=2,default=str))
