from pathlib import Path
import json, pandas as pd

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'research_outputs/amd_full_clean_frozen_transfer'
clean=pd.read_parquet(ROOT/'research_outputs/amd_canonical_test_dataset/amd_clean_testable_days.parquet')
strategies={'QQQ_CONTROLLED_RESET':'Controlled Reset','H006_RECOVERY_STABILIZATION':'Recovery Stabilization After Reset','H016_SMA50_RECLAIM':'SMA50 Reclaim After Weakness'}
rows=[]; sections=[]
for sid,name in strategies.items():
    q=pd.read_csv(OUT/(sid.lower()+'_qualifying_days.csv'),parse_dates=['date'])
    sig=pd.read_csv(OUT/(sid.lower()+'_signal_dates.csv'),parse_dates=['date'])
    life=pd.read_parquet(ROOT/f'research_outputs/amd_full_clean_{sid.lower()}/lifecycle_results.parquet')
    life['entry_date']=pd.to_datetime(life['entry_date']); life['realized_pnl']=pd.to_numeric(life.realized_pnl)
    sections.append(f'## {name}\n\nFrozen definition: '+json.loads((OUT/(sid+'.yaml')).read_text().split('signal_definition: ',1)[1].split('\n',1)[0])['strategy_id']+'; see YAML and QQQ frozen spec.\n')
    for y in range(2020,2027):
        cy=clean[clean.date.dt.year.eq(y)]; qy=q[q.date.dt.year.eq(y)]; sy=sig[sig.date.dt.year.eq(y)]; ly=life[life.entry_date.dt.year.eq(y)]
        rows.append({'strategy':name,'year':y,'clean_testable_days':len(cy),'feature_ready_days':int(cy.testable_day.sum()),'qualifying_days':len(qy),'signal_dates':len(sy),'executable_trades':len(ly),'completed_lifecycles':int((ly.status=='COMPLETE').sum()),'pnl':ly.realized_pnl.sum(),'expectancy':ly.realized_pnl.mean() if len(ly) else None,'win_rate':(ly.realized_pnl>0).mean() if len(ly) else None,'stop_rate':ly.stop_triggered.mean() if len(ly) else None,'tail_loss_count':int((ly.realized_pnl<=-100).sum())})
    ly=life; rows.append({'strategy':name,'year':'TOTAL','clean_testable_days':len(clean),'feature_ready_days':len(clean),'qualifying_days':len(q),'signal_dates':len(sig),'executable_trades':len(ly),'completed_lifecycles':int((ly.status=='COMPLETE').sum()),'pnl':ly.realized_pnl.sum(),'expectancy':ly.realized_pnl.mean(),'win_rate':(ly.realized_pnl>0).mean(),'stop_rate':ly.stop_triggered.mean(),'tail_loss_count':int((ly.realized_pnl<=-100).sum())})
df=pd.DataFrame(rows); df.to_csv(OUT/'amd_full_clean_frozen_transfer_yearly_metrics.csv',index=False)
md=['# AMD Full Clean Frozen Recovery Transfer Report','', 'The complete canonical clean testable AMD population was evaluated: 1,299 rows, 2020-10-15 through 2026-07-02, within the authoritative 2020-01-02 through 2026-08-18 window. 2026 is included; it was previously exposed for diagnostics. No FINAL OOS was read.','', 'The three strategies are exact frozen QQQ definitions; no AMD-specific prefilter, threshold, or strategy definition was added. The 20 constructive-recovery episodes were not used as a proxy for all 74 breakdown episodes.', '', '## Data fitness', '', '- STRUCTURAL_DIAGNOSTIC_READY: YES — canonical clean PIT dataset, feature-complete testable rows, and full clean scan completed.', '- FIXED_PCS_REPLAY_READY: YES — exact frozen signal dates were passed to the canonical contract selector and lifecycle adapter; all replay outputs have completed lifecycles.', '- FULL_PRODUCTION_REPLAY_READY: NO — research remains isolated; no production promotion, live trading, or FINAL OOS authorization exists.', '', '## Replay funnel metrics', '', df.to_markdown(index=False), '', '## Source and scope', '', '- Underlying: canonical AMD daily research source routed through PCSDataAccess; clean dataset artifact: `amd_clean_testable_days.parquet`.', '- Options: canonical AMD options route through PCSDataAccess; replay used only valid bid/ask and post-trade-date expirations, with 30–45 DTE contract selection.', '- Route: per-ticker canonical source routing; lifecycle quotes were as-of entry and through the selected expiration.', '- Earliest/latest options source dates are recorded in `amd_data_quality_report.json` and the replay manifests.', '- Remaining gaps: physical source still contains 31 invalid bid/ask rows and same-day expirations outside the clean executable subset; full-history global readiness has unrelated pre-2020 session/basis blockers; production approval and untouched OOS access remain unavailable.', '', '## Safety', '', '`STRATEGY_DEFINITIONS_CHANGED=NO`; `THRESHOLDS_CHANGED=NO`; `LIFECYCLE_CHANGED=NO`; `PRODUCTION_RULES_CHANGED=NO`; `FINAL_OOS_TOUCHED=NO`.']
(OUT/'AMD_FULL_CLEAN_FROZEN_TRANSFER_REPORT.md').write_text('\n'.join(md),encoding='utf-8')
