"""Complete isolated executable lifecycle marks and compare frozen exits."""
from pathlib import Path
import json
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'research_outputs/nvda_duplicate_resolved_view_20260820'
def run():
 pop=pd.read_parquet(ROOT/'research_outputs/nvda_v2_v2_replay.parquet'); pop.date=pd.to_datetime(pop.date).dt.normalize(); pop.expiration=pd.to_datetime(pop.expiration).dt.normalize(); pop['candidate_id']=pop.apply(lambda r:'|'.join([str(r.ticker),r.date.date().isoformat(),r.expiration.date().isoformat(),format(float(r.short_strike),'.15g'),format(float(r.long_strike),'.15g')]),axis=1); q=pd.read_parquet(OUT/'nvda_daily_option_quotes.parquet'); q.trade_date=pd.to_datetime(q.trade_date).dt.normalize(); q=q.sort_values(['candidate_id','trade_date','strike']); marks=[]; parity=[]; gaps=[]
 for r in pop.itertuples():
  g=q[q.candidate_id==r.candidate_id]; by={d:x for d,x in g.groupby('trade_date')}; path=[]
  for d in pd.date_range(r.date,r.expiration,freq='D'):
   x=by.get(d,pd.DataFrame()); s=x[x.strike==float(r.short_strike)] if len(x) else x; l=x[x.strike==float(r.long_strike)] if len(x) else x; valid=len(s)==1 and len(l)==1 and all(pd.notna(s.iloc[0].get(c)) and pd.notna(l.iloc[0].get(c)) for c in ['bid','ask']) and s.bid.iloc[0]<=s.ask.iloc[0] and l.bid.iloc[0]<=l.ask.iloc[0]
   row={'candidate_id':r.candidate_id,'date':d,'days_since_entry':(d-r.date).days,'short_bid':s.bid.iloc[0] if len(s) else None,'short_ask':s.ask.iloc[0] if len(s) else None,'long_bid':l.bid.iloc[0] if len(l) else None,'long_ask':l.ask.iloc[0] if len(l) else None,'mark_valid':bool(valid),'source_gap':not bool(valid),'provenance':'isolated_duplicate_resolved_view'}
   if valid: row['spread_mark']=float(s.ask.iloc[0]-l.bid.iloc[0]); path.append((d,row['spread_mark']))
   else: row['spread_mark']=None; gaps.append({'candidate_id':r.candidate_id,'date':d,'classification':'EXIT_PARITY_UNOBSERVABLE_SOURCE_GAP'})
   marks.append(row)
  initial=float(r.credit); usable=[x for x in path if x[0] <= r.date+pd.Timedelta(days=20)]; profit=next(((d,m) for d,m in usable if m<=initial*.5),None); stop=next(((d,m) for d,m in usable if m>=initial*2),None); chosen=(profit,'PROFIT_CAPTURE') if profit and (not stop or profit[0]<=stop[0]) else (stop,'STOP') if stop else ((usable[-1],'TIME_EXIT') if usable else (None,'UNAVAILABLE')); rec={'candidate_id':r.candidate_id,'authoritative_exit_date':r.exit_date,'authoritative_exit_reason':r.exit_reason,'authoritative_pnl':r.realized_pnl,'reconstructed_exit_date':chosen[0][0] if chosen[0] else None,'reconstructed_exit_reason':chosen[1],'reconstructed_pnl':(initial-chosen[0][1])*100 if chosen[0] else None,'observable_path':len(usable)>=min(20,len(pd.bdate_range(r.date,min(r.expiration,r.date+pd.Timedelta(days=20))))),'mismatch_type':None}; parity.append(rec)
 m=pd.DataFrame(marks); m.to_parquet(OUT/'nvda_daily_lifecycle_marks.parquet',index=False); gaps=pd.DataFrame(gaps); gaps.to_parquet(OUT/'nvda_unobservable_exit_candidates.parquet',index=False); p=pd.DataFrame(parity); obs=p[p.observable_path]; date_ok=(pd.to_datetime(obs.authoritative_exit_date)==pd.to_datetime(obs.reconstructed_exit_date)); reason_ok=obs.authoritative_exit_reason==obs.reconstructed_exit_reason; pnl_ok=(obs.authoritative_pnl-obs.reconstructed_pnl).abs()<=1e-6; mism=obs.loc[~(date_ok&reason_ok&pnl_ok)].copy(); mism['mismatch_type']='ARTIFACT_INCONSISTENCY'; mism.to_parquet(OUT/'nvda_exit_parity_mismatches.parquet',index=False); result={'frozen_candidates':826,'required_lifecycle_rows':len(m),'valid_spread_mark_rows':int(m.mark_valid.sum()),'source_coverage_rate':float(m.mark_valid.mean()),'source_gap_rows':int((~m.mark_valid).sum()),'fully_observable_trades':len(obs),'exit_date_matches':int(date_ok.sum()),'exit_reason_matches':int(reason_ok.sum()),'pnl_matches':int(pnl_ok.sum()),'observable_mismatches':len(mism),'unobservable_trades':int((~p.observable_path).sum()),'regime_status':'NVDA_REGIME_HISTORY_BLOCKED_BY_CANONICAL_MARKET_INPUTS'}; (OUT/'nvda_exit_parity.json').write_text(json.dumps(result,indent=2,default=str),encoding='utf-8'); (OUT/'nvda_lifecycle_mark_validation.json').write_text(json.dumps({'status':'COMPLETE' if not len(mism) else 'PARTIAL','mark_method':'short_ask_minus_long_bid; canonical executable close estimate','result':result},indent=2,default=str),encoding='utf-8'); return result
if __name__=='__main__': print(json.dumps(run(),indent=2,default=str))
