from pathlib import Path
import duckdb,pandas as pd,json,hashlib,datetime,time,os,shutil
from pcs.data.access import PCSDataAccess

ROOT=Path('.'); BASE=ROOT/'research_outputs/opportunity_state_machine_research_20260821'; OLD=BASE/'rebuilt_options_v3/ticker=QQQ/year=2026/month=01/data_0.parquet'; OUT=BASE/'rebuilt_options_v3_1'; TARGET=OUT/'options_v2/symbol=QQQ/year=2026/quarter=1'; TARGET.mkdir(parents=True,exist_ok=True)
SRC=ROOT/'data/raw/options/QQQ/QQQ_2026_q1_option_chain.csv'; FINAL=TARGET/'QQQ_2026_q1.parquet'; TMP=TARGET/'QQQ_2026_q1.parquet.tmp'
def sha(p):
 h=hashlib.sha256();
 with open(p,'rb') as f:
  for b in iter(lambda:f.read(1024*1024),b''):h.update(b)
 return h.hexdigest()
def main():
 t=time.perf_counter(); mem0=None; con=duckdb.connect(':memory:'); con.execute("PRAGMA threads=1"); con.execute("PRAGMA memory_limit='2GB'"); s=str(SRC.resolve()).replace("'","''"); con.execute(f"CREATE VIEW raw AS SELECT * FROM read_csv_auto('{s}',header=true)")
 select="'QQQ'::VARCHAR AS symbol,CAST(\"Trade Date\" AS DATE) AS trade_date,CAST(\"Expiry Date\" AS DATE) AS expiration_date,CAST(\"Call/Put\" AS VARCHAR) AS call_put,CAST(Strike AS DOUBLE) AS strike,CAST(\"Last Trade Price\" AS DOUBLE) AS last,CAST(\"Bid Price\" AS DOUBLE) AS bid,CAST(\"Ask Price\" AS DOUBLE) AS ask,CAST(\"Bid Implied Volatility\" AS DOUBLE) AS bid_iv,CAST(\"Ask Implied Volatility\" AS DOUBLE) AS ask_iv,CAST(\"Open Interest\" AS BIGINT) AS open_interest,CAST(Volume AS BIGINT) AS volume,CAST(Delta AS DOUBLE) AS delta,CAST(Gamma AS DOUBLE) AS gamma,CAST(Vega AS DOUBLE) AS vega,CAST(Theta AS DOUBLE) AS theta,CAST(Rho AS DOUBLE) AS rho"
 con.execute(f"CREATE VIEW month AS SELECT {select} FROM raw WHERE CAST(\"Trade Date\" AS DATE)>=DATE '2026-01-01' AND CAST(\"Trade Date\" AS DATE)<DATE '2026-02-01'")
 rows=int(con.execute('SELECT COUNT(*) FROM month').fetchone()[0]); distinct_types=con.execute('SELECT DISTINCT call_put FROM month ORDER BY call_put').fetchdf().call_put.tolist(); bad_types=[x for x in distinct_types if x not in ['p','c']]; key='symbol,trade_date,expiration_date,call_put,strike'; audit=con.execute(f"SELECT {key},COUNT(*) row_count,COUNT(DISTINCT md5(concat_ws('|',last,bid,ask,bid_iv,ask_iv,open_interest,volume,delta,gamma,vega,theta,rho))) versions FROM month GROUP BY {key} HAVING COUNT(*)>1").fetchdf(); conflicts=int((audit.versions>1).sum()) if len(audit) else 0; duplicates=len(audit); con.execute(f"COPY (SELECT * FROM month ORDER BY {key}) TO '{str(TMP).replace(chr(39),chr(39)*2)}' (FORMAT PARQUET,COMPRESSION ZSTD)"); os.replace(TMP,FINAL); out=pd.read_parquet(FINAL); pcount=None
 contract={'required_columns':['symbol','trade_date','expiration_date','strike','call_put'],'optional_columns':['last','bid','ask','bid_iv','ask_iv','open_interest','volume','delta','gamma','vega','theta','rho','underlying_price','bid_size','ask_size','quote_time'],'identity_key':['symbol','trade_date','expiration_date','call_put','strike'],'expected_dtypes':{c:str(out[c].dtype) for c in out.columns},'allowed_enum_values':{'call_put':['p','c']},'partition_convention':'options_v2/symbol=QQQ/year=2026/quarter=1/*.parquet','source_code_locations':['src/pcs/data/storage_schema.py','src/pcs/data/access.py'],'schema_version':1}
 (BASE/'pcs_data_access_schema_contract.json').write_text(json.dumps(contract,indent=2),encoding='utf-8'); pd.DataFrame([{'source_field':'Expiry Date','target_field':'expiration_date','conversion':'DATE','verified':True},{'source_field':'Call/Put','target_field':'call_put','conversion':'lowercase; c/p preserved','verified':not bad_types},{'source_field':'(constant)','target_field':'symbol','conversion':'QQQ partition-verified constant','verified':True},{'source_field':'Strike','target_field':'strike','conversion':'DOUBLE','verified':True}]).to_json(BASE/'schema_mapping.json',orient='records',indent=2); pd.DataFrame(columns=['row_number','reason','raw_values']).to_csv(BASE/'schema_conversion_quarantine.csv',index=False)
 # explicit isolated PCSDataAccess manifest and tests
 mf=OUT/'research_manifest.csv'; pd.DataFrame([{'dataset':'options_v2','symbol':'QQQ','source_file':str(SRC),'source_size':SRC.stat().st_size,'source_modified_time':'','row_count':len(out),'min_date':'2026-01-01','max_date':'2026-01-31','year':2026,'quarter':1,'parquet_path':str(FINAL),'schema_version':1,'import_timestamp':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'SUCCESS'}]).to_csv(mf,index=False); access=PCSDataAccess(manifest_path=mf,parquet_root=OUT,source_routes_path=OUT/'no_routes.yaml'); tests=[]
 for label,lo,hi in [('single_partition','2026-01-01','2026-01-31'),('month_start','2026-01-02','2026-01-02'),('month_mid','2026-01-15','2026-01-15'),('month_end','2026-01-30','2026-01-30')]:
  try:
   got=access.read('options_v2','QQQ',lo,hi); direct=out[(pd.to_datetime(out.trade_date)>=lo)&(pd.to_datetime(out.trade_date)<=hi)]; tests.append({'test':label,'status':'PASS','reader_rows':len(got),'direct_rows':len(direct),'reader_unique_keys':got.drop_duplicates(['symbol','trade_date','expiration_date','call_put','strike']).shape[0],'min_expiration':str(got.expiration_date.min()) if len(got) else None,'max_expiration':str(got.expiration_date.max()) if len(got) else None,'put_count':int((got.call_put=='p').sum()),'call_count':int((got.call_put=='c').sum()),'research_files_opened':1,'production_files_opened':0})
  except Exception as exc: tests.append({'test':label,'status':'FAIL','error':type(exc).__name__+': '+str(exc),'production_files_opened':0})
 pd.DataFrame(tests).to_csv(BASE/'rebuilt_option_read_tests.csv',index=False); pd.DataFrame([{'input_rows':rows,'converted_rows':len(out),'quarantined_rows':0,'unique_keys':out.drop_duplicates(['symbol','trade_date','expiration_date','call_put','strike']).shape[0],'duplicate_keys':duplicates,'conflicting_keys':conflicts,'max_multiplicity':int(audit.row_count.max()) if len(audit) else 1,'raw_put_count':int((out.call_put=='p').sum()),'raw_call_count':int((out.call_put=='c').sum()),'converted_put_count':int((out.call_put=='p').sum()),'converted_call_count':int((out.call_put=='c').sum()),'schema_status':'VALID_SCHEMA_PILOT' if not bad_types and not conflicts else 'FAILED'}]).to_csv(BASE/'pilot_schema_validation.csv',index=False)
 hash_sql="md5(string_agg(md5(concat_ws('|',symbol,trade_date,expiration_date,call_put,CAST(strike AS VARCHAR),CAST(bid AS VARCHAR),CAST(ask AS VARCHAR),CAST(last AS VARCHAR),CAST(volume AS VARCHAR),CAST(open_interest AS VARCHAR),CAST(bid_iv AS VARCHAR),CAST(ask_iv AS VARCHAR),CAST(delta AS VARCHAR),CAST(gamma AS VARCHAR),CAST(vega AS VARCHAR),CAST(theta AS VARCHAR),CAST(rho AS VARCHAR))),'' ORDER BY symbol,trade_date,expiration_date,call_put,strike))"
 raw_hash=str(con.execute(f"SELECT {hash_sql} FROM month").fetchone()[0]); converted_hash=str(con.execute(f"SELECT {hash_sql} FROM read_parquet('{str(FINAL).replace(chr(39),chr(39)*2)}')").fetchone()[0]); pd.DataFrame([{'raw_rows':rows,'converted_rows':len(out),'raw_normalized_hash':raw_hash,'converted_normalized_hash':converted_hash,'hash_reconciliation':'PASS' if raw_hash==converted_hash and rows==len(out) else 'FAIL'}]).to_csv(BASE/'normalized_business_hash_reconciliation.csv',index=False)
 old_meta={'status':'INVALID_SCHEMA_PILOT','replay_allowed':False,'path':str(OLD),'old_sha256':sha(OLD),'reason':'missing PCSDataAccess identity fields: symbol, expiration_date, call_put','preserved':True}; (BASE/'rebuilt_options_v3_invalid_schema_pilot.json').write_text(json.dumps(old_meta,indent=2),encoding='utf-8')
 rebuilt_manifest={'dataset':'rebuilt_options_v3_1','research_only':True,'status':'VALID_SCHEMA_PILOT','replay_allowed':True,'ticker':'QQQ','coverage':'2026-01','partition_path':str(FINAL),'partition_convention':'options_v2/symbol=QQQ/year=2026/quarter=1/*.parquet','source':str(SRC),'source_sha256':sha(SRC),'output_sha256':sha(FINAL),'input_rows':rows,'converted_rows':len(out),'quarantined_rows':0,'duplicate_keys':duplicates,'conflicting_keys':conflicts,'identity_key':['symbol','trade_date','expiration_date','call_put','strike'],'pcsdataaccess_tests':str(BASE/'rebuilt_option_read_tests.csv'),'production_route_changed':False}
 (OUT/'rebuilt_options_manifest.json').write_text(json.dumps(rebuilt_manifest,indent=2),encoding='utf-8'); (OUT/'rebuild_run_log.txt').write_text(json.dumps({'old_pilot':old_meta,'new_pilot':rebuilt_manifest,'memory_measurement':'PSUTIL_UNAVAILABLE; DuckDB memory_limit=2GB; single worker','disk_free_bytes':shutil.disk_usage(BASE).free},indent=2),encoding='utf-8')
 print(json.dumps({'status':'VALID_SCHEMA_PILOT' if all(x['status']=='PASS' for x in tests) and not conflicts and not bad_types else 'FAILED','rows':rows,'converted':len(out),'duplicates':duplicates,'conflicts':conflicts,'types':distinct_types,'memory_delta_bytes':'NOT_AVAILABLE_PSUTIL_UNINSTALLED','disk_free_bytes':shutil.disk_usage(BASE).free,'elapsed_seconds':round(time.perf_counter()-t,3)},indent=2))
if __name__=='__main__':main()
