from pathlib import Path
import json, pandas as pd
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'research_outputs/frozen_strategy_regression/NVDA'
rows=pd.read_csv(OUT/'frozen_reference_diff.csv')
audit=json.loads((OUT/'signal_population_audit.json').read_text())
for _,r in rows.iterrows():
    sid=r['strategy']; p=OUT/f"nvda_{sid.lower()[3:]}_current_metrics.json"; d=json.loads(p.read_text()); d['interpretation']='Signal population differs before contract/lifecycle; current economic-trade metrics are one-selected-trade-per-signal and not old-reference parity until old coverage is reconstructed.'; p.write_text(json.dumps(d,indent=2,default=str))
lines=['# NVDA Frozen Strategy Regression Report','', '## Scope and controls','', '- Readiness: PASS (`PCS_RESEARCH_READY=YES`).', '- Strategies: FIXED `V2_H010` and `V2_H027`; no adaptive config, recalibration, threshold changes, production changes, or FINAL OOS access.', '- RegimeGate: disabled as a blocker per current research replay rule.', '- Economic semantics: one canonical selected contract per signal/episode; all alternative contract candidates are excluded from aggregate metrics.', '', '## Signal population audit','', 'The first difference is the signal population. Current full-calendar discovery produces 35 H010 episodes versus 26 in the old artifact, and 20 H027 versus 17. The old PIT outcome artifact begins at 2020-12-10; most CURRENT_ONLY dates are earlier dates absent from that artifact, so the difference is currently attributable to **PIT population coverage / old reference population boundary**, not demonstrated feature-value drift. On COMMON and OLD_ONLY dates, the stored feature values match the current canonical daily reconstruction for close, SMA200, ret5, ret20, and volume ratio.', '', 'The detailed date-by-date evidence is in `signal_date_diff.csv`; membership is `OLD_ONLY`, `CURRENT_ONLY`, or `COMMON`.', '', '## Economic replay','', rows.to_string(index=False), '', 'The current selected-trade counts are lower than signal counts because some dates have no executable canonical contract. They are not comparable to the old 26/17 completed-trade references until the old reference date/contract population is reconstructed over the same full calendar.', '', '## Conclusion','', '**UNEXPLAINED_SIGNAL_POPULATION_DIFFERENCE**', '', 'This is not evidence that NVDA strategy performance has failed. The execution-layer regression is not yet apples-to-apples; no strategy or production code was changed. FINAL OOS remains untouched.']
(OUT/'NVDA_FROZEN_REGRESSION_REPORT.md').write_text('\n'.join(lines),encoding='utf-8')
print(rows.to_json(orient='records',indent=2))
