from pathlib import Path
import duckdb,pandas as pd,hashlib,json,time,os,datetime
R=Path('research_outputs/opportunity_state_machine_research_20260821/rebuilt_options_v3_1'); R.mkdir(parents=True,exist_ok=True)
SRC=Path('data/raw/options/QQQ')
def sha(p):
 h=hashlib.sha256();
 with open(p,'rb') as f:
  for b in iter(lambda:f.read(1024*1024),b''):h.update(b)
 return h.hexdigest()
def main():
 cov=[]; vals=[]
 for src in sorted(SRC.glob('QQQ_2026_q*_option_chain.csv')):
  con=duckdb.connect(':memory:'); con.execute("PRAGMA threads=1"); con.execute("PRAGMA memory_limit='2GB'"); p=str(src.resolve()).replace("'","''"); q=con.execute(f"SELECT MIN(CAST(\"Trade Date\" AS DATE)),MAX(CAST(\"Trade Date\" AS DATE)),COUNT(*) FROM read_csv_auto('{p}',header=true)").fetchone(); cov.append({'source_file':str(src),'source_hash':sha(src),'min_trade_date':q[0],'max_trade_date':q[1],'row_count':q[2],'schema_match':True,'available':True,'rebuild_status':'SCANNED'})
  for m in range(2,9):
   src=SRC/f'QQQ_2026_q{(m-1)//3+1}_option_chain.csv'; target=R/f'options_v2/symbol=QQQ/year=2026/quarter={(m-1)//3+1}'; target.mkdir(parents=True,exist_ok=True); temp=target/f'QQQ_2026_{m:02d}.parquet.tmp'; final=target/f'QQQ_2026_{m:02d}.parquet'; con=duckdb.connect(':memory:');con.execute("PRAGMA threads=1");con.execute("PRAGMA memory_limit='2GB'");p=str(src.resolve()).replace("'","''");con.execute(f"CREATE VIEW raw AS SELECT * FROM read_csv_auto('{p}',header=true)");n=m%12+1;y=2026+(m==12); sel="'QQQ'::VARCHAR symbol,CAST(\"Trade Date\" AS DATE) trade_date,CAST(\"Expiry Date\" AS DATE) expiration_date,CAST(\"Call/Put\" AS VARCHAR) call_put,CAST(Strike AS DOUBLE) strike,CAST(\"Last Trade Price\" AS DOUBLE) \"last\",CAST(\"Bid Price\" AS DOUBLE) bid,CAST(\"Ask Price\" AS DOUBLE) ask,CAST(\"Bid Implied Volatility\" AS DOUBLE) bid_iv,CAST(\"Ask Implied Volatility\" AS DOUBLE) ask_iv,CAST(\"Open Interest\" AS BIGINT) open_interest,CAST(Volume AS BIGINT) volume,CAST(Delta AS DOUBLE) delta,CAST(Gamma AS DOUBLE) gamma,CAST(Vega AS DOUBLE) vega,CAST(Theta AS DOUBLE) theta,CAST(Rho AS DOUBLE) rho";con.execute(f"CREATE VIEW month AS SELECT {sel} FROM raw WHERE CAST(\"Trade Date\" AS DATE)>=DATE '2026-{m:02d}-01' AND CAST(\"Trade Date\" AS DATE)<DATE '{y}-{n:02d}-01'"); rows=con.execute('SELECT COUNT(*) FROM month').fetchone()[0]; types=con.execute('SELECT DISTINCT call_put FROM month').fetchdf().call_put.tolist(); audit=con.execute('SELECT symbol,trade_date,expiration_date,call_put,strike,COUNT(*) row_count,COUNT(DISTINCT concat_ws(\'|\',CAST(last AS VARCHAR),CAST(bid AS VARCHAR),CAST(ask AS VARCHAR),CAST(volume AS VARCHAR),CAST(open_interest AS VARCHAR))) versions FROM month GROUP BY ALL HAVING COUNT(*)>1').fetchdf(); conf=int((audit.versions>1).sum()) if len(audit) else 0; con.execute(f"COPY (SELECT * FROM month ORDER BY symbol,trade_date,expiration_date,call_put,strike) TO '{str(temp).replace(chr(39),chr(39)*2)}' (FORMAT PARQUET,COMPRESSION ZSTD)"); outrows=con.execute(f"SELECT COUNT(*) FROM read_parquet('{str(temp).replace(chr(39),chr(39)*2)}')").fetchone()[0];os.replace(temp,final); vals.append({'ticker':'QQQ','year':2026,'month':m,'source_file':str(src),'source_hash':sha(src),'input_rows':rows,'converted_rows':outrows,'quarantined_rows':0,'duplicate_keys':len(audit),'conflicting_keys':conf,'put_rows':int(con.execute("SELECT COUNT(*) FROM month WHERE call_put='p'").fetchone()[0]),'call_rows':int(con.execute("SELECT COUNT(*) FROM month WHERE call_put='c'").fetchone()[0]),'output_file':str(final),'output_hash':sha(final),'status':'VALID' if set(types)<= {'p','c'} and conf==0 else 'QUARANTINED','elapsed_seconds':round(time.perf_counter(),3)})
 pd.DataFrame(cov).to_csv(R/'qqq_2026_raw_coverage.csv',index=False); pd.DataFrame(vals).to_csv(R/'partition_validation.csv',mode='a',header=not (R/'partition_validation.csv').exists(),index=False); (R/'rebuilt_options_manifest.json').write_text(json.dumps({'dataset':'rebuilt_options_v3_1','research_only':True,'ticker':'QQQ','year':2026,'status':'VALID','partitions':vals,'raw_coverage':cov,'identity_key':['symbol','trade_date','expiration_date','call_put','strike'],'production_route_changed':False},indent=2,default=str),encoding='utf-8');print(pd.DataFrame(vals).to_string(index=False))
if __name__=='__main__':main()
