"""Round 48: robustness and frozen-family independence for SMA50 reclaim."""
from pathlib import Path
import json
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/"research_outputs"/"nvda_entry_discovery_agent_v2"
def ep(x):
 x=x.sort_values("trade_date").copy(); x["episode_id"]=(x.trade_date.diff().dt.days.fillna(999)>10).cumsum(); return x.groupby("episode_id",as_index=False).head(1)
def m(x):
 x=ep(x); n=x.loc[x.realized_pnl<0,"realized_pnl"].sum(); p=x.loc[x.realized_pnl>0,"realized_pnl"].sum(); return {"episodes":int(len(x)),"pnl":float(x.realized_pnl.sum()),"expectancy":float(x.realized_pnl.mean()) if len(x) else None,"profit_factor":float(p/abs(n)) if n else None,"stop_rate":float(x.stopped.mean()) if len(x) else None,"bad_cases":int(x.outcome_class.isin(["NORMAL_LOSS","STOP_LOSS","TAIL_LOSS"]).sum()),"years":sorted(int(y) for y in x.year.dropna().unique())}
def run():
 d=pd.read_parquet(OUT/"pit_feature_outcome_table.parquet").copy(); d.trade_date=pd.to_datetime(d.trade_date).dt.normalize(); d.date=pd.to_datetime(d.date).dt.normalize(); d=d[(d.ticker=="NVDA")&d.trade_date.between("2020-01-02","2023-12-31")].sort_values("trade_date").copy(); d["prior_sma50"]=d.nvda_close_vs_sma50.shift(1); d["prior_drawdown"]=d.nvda_drawdown20.shift(1); mask=(d.prior_sma50<=0)&(d.nvda_close_vs_sma50>0)&(d.prior_drawdown<0); d=d[d.executable_pcs].copy(); trend=(d.nvda_close_vs_sma200>0)&(d.nvda_volume_rel20>1)&(d.nvda_ret5>0); recovery=(d.nvda_close_vs_sma200>0)&(d.nvda_ret20<0)&(d.nvda_ret5>0); mask=mask.reindex(d.index,fill_value=False); x=d[mask]; e=ep(x); out={"module":"pcs.research.nvda_sma50_reclaim_round48","version":"1.0","symbol":"NVDA","status":"DESCRIPTIVE_ONLY","data_source":"PCS_CANONICAL_DATA","research_mode":"EXISTING_TRADE","input_rows":int(len(d)),"candidate_rows":int(len(x)),"full_sample":m(x),"outside_frozen_families":m(d[mask&~trend&~recovery]),"overlap_trend":m(d[mask&trend]),"overlap_recovery":m(d[mask&recovery]),"leave_one_year_out":[{"left_out_year":int(y),**m(e[e.year!=y])} for y in sorted(int(y) for y in e.year.dropna().unique())],"pnl_concentration":{"top_3_share":float(e.sort_values('realized_pnl',ascending=False).head(3).realized_pnl.sum()/e.realized_pnl.sum()),"worst_trade":float(e.realized_pnl.min())},"decision":"RESEARCH_PROMISING_BUT_INSUFFICIENT","validation_read":False,"final_oos_read":False,"production_changes":False,"frozen_rule_families_unchanged":["PCS_TREND_CONTINUATION","PCS_CONSTRUCTIVE_RECOVERY"],"reason_codes":["NVDA_ONLY","FULL_PIT_CALENDAR_BEFORE_EXECUTABLE_FILTER","INDEPENDENT_EPISODE_ANALYSIS","FROZEN_FAMILY_INDEPENDENCE_AUDIT","LEAVE_ONE_YEAR_OUT","NO_VALIDATION","NO_FINAL_OOS","NO_PRODUCTION_CHANGE"]}; (OUT/"v2_round48_sma50_reclaim_robustness.json").write_text(json.dumps(out,indent=2),encoding="utf-8"); return out
if __name__=="__main__": print(json.dumps(run(),indent=2))
