from pathlib import Path
import json, numpy as np, pandas as pd
ROOT=Path(__file__).resolve().parents[1]; SRC=ROOT/'research_outputs/nvda_research_agent/round16_deep_entry_sequence_20260824'; OUT=ROOT/'research_outputs/nvda_research_agent/round17_market_archetypes_20260824'; OUT.mkdir(parents=True,exist_ok=True)
d=pd.read_parquet(SRC/'train_sequence_rows.parquet')
d['market_agree']=d.sequence_state.isin(['UNKNOWN','STABILIZING','MA20_RECLAIM','POST_RECLAIM_CONTINUATION']) & d.qqq_above50.fillna(False); d['market_weak']=~d.qqq_above50.fillna(False); d['archetype']='OTHER'
d.loc[d.sequence_state.eq('ACCELERATING_DOWNSIDE')&d.market_weak,'archetype']='ACCELERATING_DOWNSIDE_MARKET_WEAK'; d.loc[d.sequence_state.isin(['UNKNOWN','STABILIZING'])&d.market_agree,'archetype']='STABLE_MARKET_AGREEMENT'; d.loc[d.sequence_state.isin(['MA20_RECLAIM','POST_RECLAIM_CONTINUATION'])&d.market_agree,'archetype']='RECLAIM_MARKET_AGREEMENT'; d.loc[d.sequence_state.isin(['DECELERATING_DOWNSIDE','STABILIZING'])&d.market_weak,'archetype']='RECOVERY_WITH_MARKET_WEAKNESS'
def m(g):
 w=g.pnl>0; return pd.Series({'n':len(g),'pnl':g.pnl.sum(),'expectancy':g.pnl.mean(),'pf':g.loc[w,'pnl'].sum()/abs(g.loc[~w,'pnl'].sum()) if (~w).any() else np.inf,'win_rate':w.mean(),'stop_rate':g.stop.mean(),'worst10_n':int((g.pnl<=g.pnl.quantile(.1)).sum())})
summary=d.groupby('archetype',dropna=False).apply(m,include_groups=False).reset_index(); summary.to_csv(OUT/'archetype_summary.csv',index=False); annual=d.groupby(['year','archetype'],dropna=False).apply(m,include_groups=False).reset_index(); annual.to_csv(OUT/'archetype_annual.csv',index=False); ctx=d.groupby(['market_agree','sequence_state'],dropna=False).apply(m,include_groups=False).reset_index(); ctx.to_csv(OUT/'market_context_by_state.csv',index=False); d.to_parquet(OUT/'train_market_archetype_rows.parquet',index=False)
json.dump({'research_id':'nvda_deep_entry_round17','ticker':'NVDA','research_mode':'EXISTING_TRADE','population':'corrected frozen TRAIN lifecycle ledger','final_oos_read':False,'validation_read':False,'production_changes':False,'status':'DESCRIPTIVE_ONLY'},open(OUT/'study_manifest.json','w'),indent=2); print(summary.to_string()); print('\nAnnual:\n',annual.to_string(index=False))
