"""Round 39 robustness for NVDA relative-strength divergence."""
from pathlib import Path
import json
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/"research_outputs"/"nvda_entry_discovery_agent_v2"
def ep(x):
 x=x.sort_values("trade_date").copy(); x["episode_id"]=(x.trade_date.diff().dt.days.fillna(999)>10).cumsum(); return x.groupby("episode_id",as_index=False).head(1)
def m(x):
 x=ep(x); n=x.loc[x.realized_pnl<0,"realized_pnl"].sum(); p=x.loc[x.realized_pnl>0,"realized_pnl"].sum(); return {"episodes":int(len(x)),"pnl":float(x.realized_pnl.sum()),"expectancy":float(x.realized_pnl.mean()) if len(x) else None,"profit_factor":float(p/abs(n)) if n else None,"stop_rate":float(x.stopped.mean()) if len(x) else None,"tail_losses":int((x.outcome_class=="TAIL_LOSS").sum()),"years":sorted(int(y) for y in x.year.dropna().unique())}
def run():
 d=pd.read_parquet(OUT/"pit_feature_outcome_table.parquet").copy(); d.trade_date=pd.to_datetime(d.trade_date).dt.normalize(); d.date=pd.to_datetime(d.date).dt.normalize(); d=d[(d.ticker=="NVDA")&d.executable_pcs&d.trade_date.between("2020-01-02","2023-12-31")].copy(); x=d[(d.nvda_ret20<=0)&(d.qqq_ret20>0)&(d.nvda_ret5>0)]; e=ep(x); loo=[{"left_out_year":int(y),**m(e[e.year!=y])} for y in sorted(int(y) for y in e.year.dropna().unique())]; r=e.sort_values("realized_pnl",ascending=False); total=e.realized_pnl.sum(); out={"module":"pcs.research.nvda_relative_divergence_round39","version":"1.0","symbol":"NVDA","status":"DESCRIPTIVE_ONLY","data_source":"PCS_CANONICAL_DATA","research_mode":"EXISTING_TRADE","input_rows":int(len(d)),"candidate_rows":int(len(x)),"pit_feature_date_equals_trade_date":bool((d.date==d.trade_date).all()),"full_sample":m(x),"leave_one_year_out":loo,"pnl_concentration":{"top_1_share":float(r.head(1).realized_pnl.sum()/total) if total else None,"top_3_share":float(r.head(3).realized_pnl.sum()/total) if total else None,"worst_trade":float(e.realized_pnl.min()) if len(e) else None},"decision":"RESEARCH_PROMISING_BUT_INSUFFICIENT","validation_read":False,"final_oos_read":False,"production_changes":False,"frozen_rule_families_unchanged":["PCS_TREND_CONTINUATION","PCS_CONSTRUCTIVE_RECOVERY"],"reason_codes":["NVDA_ONLY","TRAIN_ONLY","INDEPENDENT_EPISODE_ANALYSIS","LEAVE_ONE_YEAR_OUT","PNL_CONCENTRATION","SMALL_SAMPLE","NO_VALIDATION","NO_FINAL_OOS","NO_PRODUCTION_CHANGE"]}; (OUT/"v2_round39_relative_divergence_robustness.json").write_text(json.dumps(out,indent=2),encoding="utf-8"); return out
if __name__=="__main__": print(json.dumps(run(),indent=2))
