"""Round 50: predeclared elevated-ATR/down-day bad-state audit."""
from pathlib import Path
import json
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/"research_outputs"/"nvda_entry_discovery_agent_v2"
def run():
 d=pd.read_parquet(OUT/"pit_feature_outcome_table.parquet").copy(); d.trade_date=pd.to_datetime(d.trade_date).dt.normalize(); d.date=pd.to_datetime(d.date).dt.normalize(); d=d[(d.ticker=="NVDA")&d.executable_pcs&d.trade_date.between("2020-01-02","2023-12-31")].copy(); atr=d.nvda_atr14.median(); bad=d.outcome_class.isin(["NORMAL_LOSS","STOP_LOSS","TAIL_LOSS"]); states={"ANY_DOWN_DAY":d.consecutive_down_days>=1,"ELEVATED_ATR":d.nvda_atr14>atr,"DOWN_DAY_AND_ELEVATED_ATR":(d.consecutive_down_days>=1)&(d.nvda_atr14>atr),"NO_DOWN_DAY_AND_NORMAL_ATR":(d.consecutive_down_days==0)&(d.nvda_atr14<=atr)}; rows=[]; yearly=[]
 for name,mask in states.items():
  x=d[mask]; y=d[~mask]; rows.append({"state_id":name,"rows_inside":int(len(x)),"bad_inside":int(bad[mask].sum()),"stop_losses":int((x.outcome_class=="STOP_LOSS").sum()),"tail_losses":int((x.outcome_class=="TAIL_LOSS").sum()),"bad_rate_inside":float(bad[mask].mean()) if len(x) else None,"bad_rate_outside":float(bad[~mask].mean()) if len(y) else None,"pnl_inside":float(x.realized_pnl.sum()),"pnl_outside":float(y.realized_pnl.sum()),"conclusion":"NO_RELIABLE_FILTER"})
  for year,g in x.groupby(x.trade_date.dt.year): yearly.append({"state_id":name,"year":int(year),"rows_inside":int(len(g)),"bad_inside":int(bad.loc[g.index].sum()),"stop_losses":int((g.outcome_class=="STOP_LOSS").sum()),"tail_losses":int((g.outcome_class=="TAIL_LOSS").sum()),"bad_rate_inside":float(bad.loc[g.index].mean()) if len(g) else None})
 pd.DataFrame(rows).to_csv(OUT/"v2_round50_atr_downstate_profiles.csv",index=False); pd.DataFrame(yearly).to_csv(OUT/"v2_round50_atr_downstate_yearly.csv",index=False); out={"module":"pcs.research.nvda_atr_downstate_round50","version":"1.0","symbol":"NVDA","status":"DESCRIPTIVE_ONLY","data_source":"PCS_CANONICAL_DATA","research_mode":"EXISTING_TRADE","input_rows":int(len(d)),"pit_feature_date_equals_trade_date":bool((d.date==d.trade_date).all()),"median_atr":float(atr),"decision":"NO_RELIABLE_FILTER","validation_read":False,"final_oos_read":False,"production_changes":False,"frozen_rule_families_unchanged":["PCS_TREND_CONTINUATION","PCS_CONSTRUCTIVE_RECOVERY"],"reason_codes":["NVDA_ONLY","TRAIN_ONLY","PIT_SAFE","PREDECLARED_BAD_STATE_SCREEN","NO_THRESHOLD_MINING","NO_FORCED_NO_TRADE","NO_VALIDATION","NO_FINAL_OOS","NO_PRODUCTION_CHANGE"]}; (OUT/"v2_round50_manifest.json").write_text(json.dumps(out,indent=2),encoding="utf-8"); return out
if __name__=="__main__": print(json.dumps(run(),indent=2))
