"""Round 61: full PIT-calendar signal frontier outside the 623 executable rows."""
from pathlib import Path
import json
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/"research_outputs"/"nvda_entry_discovery_agent_v2"
def run():
 d=pd.read_parquet(OUT/"pit_feature_outcome_table.parquet").copy(); d.trade_date=pd.to_datetime(d.trade_date).dt.normalize(); d.date=pd.to_datetime(d.date).dt.normalize(); d=d[(d.ticker=="NVDA")&d.trade_date.between("2020-01-02","2023-12-31")].copy(); non=d[~d.executable_pcs].copy(); atr=d.nvda_atr14.median(); masks={"PULLBACK_SIGNAL":(non.nvda_close_vs_sma200>0)&(non.nvda_ret5<0)&(non.nvda_drawdown20<0),"SUPPORT_RECLAIM_SIGNAL":(non.nvda_close_vs_sma20>0)&(non.nvda_close_vs_sma50>0)&(non.nvda_ret5>0),"POST_SELLOFF_SIGNAL":(non.nvda_drawdown20<=-.15)&(non.nvda_ret5>0),"RANGE_BREAKOUT_SIGNAL":(non.nvda_ret20.abs()<=.05)&(non.nvda_ret5>0)&(non.nvda_volume_rel20>=1),"VOLATILITY_EXPANSION_SIGNAL":(non.nvda_atr14>atr)&(non.nvda_ret5>0),"MARKET_CONFIRMATION_SIGNAL":(non.qqq_close_vs_sma50>0)&(non.nvda_relative_strength20>0)&(non.nvda_ret5>0)}; rows=[]
 for name,mask in masks.items():
  x=non[mask]; rows.append({"signal_id":name,"signal_dates":int(len(x)),"option_chain_available":int(x.option_chain_available.sum()),"valid_dte_available":int(x.valid_dte_available.sum()),"standardized_constructable":int(x.standardized_pcs_constructable.sum()),"liquidity_pass":int((x.liquidity_status=="PASS").sum()),"reason_codes":x.reason_code.value_counts(dropna=False).to_dict()})
 pd.DataFrame(rows).to_csv(OUT/"v2_round61_nonexec_signal_frontier.csv",index=False); out={"module":"pcs.research.nvda_nonexec_signal_frontier_round61","version":"1.0","symbol":"NVDA","status":"DESCRIPTIVE_SIGNAL_FRONTIER_ONLY","data_source":"PCS_CANONICAL_DATA","research_mode":"NEW_ENTRY","full_calendar_rows":int(len(d)),"executable_rows":int(d.executable_pcs.sum()),"non_executable_rows":int(len(non)),"pit_feature_date_equals_trade_date":bool((d.date==d.trade_date).all()),"signals":rows,"no_outcome_inference_for_nonexec":True,"validation_read":False,"final_oos_read":False,"production_changes":False,"frozen_rule_families_unchanged":["PCS_TREND_CONTINUATION","PCS_CONSTRUCTIVE_RECOVERY"],"reason_codes":["NVDA_ONLY","FULL_PIT_CALENDAR","NEW_ENTRY_SIGNAL_DISCOVERY","NO_CONTRACT_SUBSTITUTION","NO_OUTCOME_INFERENCE","NO_VALIDATION","NO_FINAL_OOS","NO_PRODUCTION_CHANGE"]}; (OUT/"v2_round61_manifest.json").write_text(json.dumps(out,indent=2,default=str),encoding="utf-8"); return out
if __name__=="__main__": print(json.dumps(run(),indent=2,default=str))
