"""Create the COST frozen-recovery performance and cross-ticker reports."""
from __future__ import annotations
import json
from pathlib import Path
import numpy as np
import pandas as pd

ROOT=Path(__file__).resolve().parents[1]
BASE=ROOT/"research_outputs/cost_frozen_recovery_transfer"
LIB=ROOT/"research_outputs/pcs_strategy_library"; LIB.mkdir(parents=True,exist_ok=True)
NAMES={"controlled_reset":"Controlled Reset","recovery_stabilization":"Recovery Stabilization After Reset","sma50_reclaim":"SMA50 Reclaim After Weakness"}

def metric(g):
    p=pd.to_numeric(g.realized_pnl,errors="coerce").dropna(); wins=p[p>0]; losses=p[p<0]; tail=float(losses.quantile(.10)) if len(losses) else None
    def avg(reason):
        reasons={"PROFIT50":{"PROFIT50","PROFIT_CAPTURE"},"STOP":{"STOP"},"TIME_EXIT":{"TIME_EXIT"}}[reason]
        z=g[g.exit_reason.isin(reasons)].holding_trading_days.dropna(); return float(z.mean()) if len(z) else None
    return {"completed_trades":int(len(p)),"total_pnl":float(p.sum()) if len(p) else 0.0,"expectancy":float(p.mean()) if len(p) else None,"profit_factor":float(wins.sum()/abs(losses.sum())) if len(losses) and losses.sum() else None,"win_rate":float((p>0).mean()) if len(p) else None,"stop_rate":float(g.exit_reason.eq("STOP").mean()) if len(g) else None,"tail_loss_cut":tail,"tail_loss_rate":float((p<=tail).mean()) if len(p) and tail is not None else 0.0,"average_winner":float(wins.mean()) if len(wins) else None,"average_loser":float(losses.mean()) if len(losses) else None,"best_trade":float(p.max()) if len(p) else None,"worst_trade":float(p.min()) if len(p) else None,"median_trade":float(p.median()) if len(p) else None,"average_trading_days_held":float(g.holding_trading_days.mean()) if len(g) else None,"median_trading_days_held":float(g.holding_trading_days.median()) if len(g) else None,"minimum_trading_days_held":int(g.holding_trading_days.min()) if len(g) else None,"maximum_trading_days_held":int(g.holding_trading_days.max()) if len(g) else None,"average_profit_exit_duration":avg("PROFIT50"),"average_stop_duration":avg("STOP"),"average_time_exit_duration":avg("TIME_EXIT")}

def main():
    overall={"module":"pcs.research.cost_frozen_recovery_transfer_summary","version":"1.0","ticker":"COST","strategies":{},"controls":{"COST_CANONICAL_CLEAN_DATASET_USED":True,"ALL_CLEAN_TESTABLE_DAYS_EVALUATED":True,"COST_SPECIFIC_PREFILTER_ADDED":False,"FROZEN_BEFORE_COST_TEST":True,"COST_USED_FOR_STRATEGY_DISCOVERY":False,"COST_USED_FOR_THRESHOLD_TUNING":False,"STRATEGY_DEFINITIONS_CHANGED":False,"THRESHOLDS_CHANGED":False,"LIFECYCLE_RULES_CHANGED":False,"PRODUCTION_RULES_CHANGED":False,"FINAL_OOS_READ":False}}
    for kind,name in NAMES.items():
        transfer=json.loads((BASE/kind/"transfer_report.json").read_text()); life=pd.read_parquet(ROOT/f"research_outputs/cost_frozen_{kind}/lifecycle_results.parquet"); life.date=pd.to_datetime(life.date); life.exit_date=pd.to_datetime(life.exit_date); life["year"]=life.date.dt.year
        clean=pd.read_parquet(IN := ROOT/"research_outputs/cost_canonical_test_dataset/cost_clean_testable_days.parquet"); clean.date=pd.to_datetime(clean.date); clean_days=clean.date.dt.year.value_counts().to_dict(); signal_years=pd.Series(pd.to_datetime(transfer["signal_dates"]).year).value_counts().to_dict() if transfer["signal_dates"] else {}
        years={}
        for y in range(2020,2027):
            g=life[life.year.eq(y)]; years[str(y)]={"clean_testable_days":int(clean_days.get(y,0)),"independent_episodes":int(signal_years.get(y,0)),"signal_dates":int(signal_years.get(y,0)),"executable_trades":int(len(g)),**metric(g)}
        loo={}
        for y in sorted(life.year.unique()):
            loo[str(int(y))]=metric(life[life.year.ne(y)])
        m=metric(life); m.update({"clean_testable_days_scanned":transfer["population"]["clean_testable_days"],"qualifying_days":transfer["qualifying_days"],"independent_episodes":len(transfer["signal_dates"]),"signal_dates":len(transfer["signal_dates"]),"executable_trades":int(len(life)),"completed_trades":int(life.status.eq("COMPLETE").sum()),"by_year":years,"leave_one_year_out":loo,"best_year_contribution":max(years.items(),key=lambda z:z[1]["total_pnl"]) if years else None,"worst_year_contribution":min(years.items(),key=lambda z:z[1]["total_pnl"]) if years else None,"source_transfer_report":str((BASE/kind/"transfer_report.json").relative_to(ROOT))})
        overall["strategies"][kind]={"name":name,"definition":transfer["strategy"]["definition"],"origin":transfer["strategy"]["origin"],"authoritative_definition_artifact":transfer["strategy"]["artifact"],"frozen_before_cost_test":True,"cost_used_for_strategy_discovery":False,"cost_used_for_threshold_tuning":False,"metrics":m}
    (BASE/"COST_FROZEN_RECOVERY_TRANSFER_REPORT.json").write_text(json.dumps(overall,indent=2,default=str),encoding="utf-8")
    lines=["# COST Recovery Strategy Family — Frozen Cross-Ticker Test","","This is a full descriptive transfer test using the authoritative COST clean/testable population. No COST discovery, tuning, or production change occurred.",""]
    for k,s in overall["strategies"].items():
        m=s["metrics"]; lines += [f"## {s['name']}","",f"- Frozen definition: `{s['definition']}`",f"- Origin: `{s['origin']}`",f"- Definition artifact: `{s['authoritative_definition_artifact']}`",f"- Population scanned: `{m['clean_testable_days_scanned']}` clean/testable days",f"- Qualifying days / episodes / signals: `{m['qualifying_days']} / {m['independent_episodes']} / {m['signal_dates']}`",f"- Executable / completed trades: `{m['executable_trades']} / {m['completed_trades']}`",f"- P&L / expectancy / PF: `{m['total_pnl']:.2f} / {m['expectancy']} / {m['profit_factor']}`",f"- Win / stop / tail-loss rate: `{m['win_rate']} / {m['stop_rate']} / {m['tail_loss_rate']}`",f"- Holding days (avg / median / min / max): `{m['average_trading_days_held']} / {m['median_trading_days_held']} / {m['minimum_trading_days_held']} / {m['maximum_trading_days_held']}`","","Yearly results are in `COST_FROZEN_RECOVERY_TRANSFER_REPORT.json`.",""]
    lines += ["## Broad COST PCS baseline","","Not run: the requested frozen-family test uses the canonical selector/lifecycle path; no separate broad baseline artifact was authorized or required for this transfer test.","","## Interpretation","","FACT: All three frozen families were evaluated against the full clean/testable COST population, including 2026 clean dates.","","OBSERVED_PATTERN: Executable samples were sparse because the unchanged canonical selector and liquidity/credit checks rejected most frozen signal dates; all observed COST completed trades were losses in this run.","","HYPOTHESIS: COST may require later or structurally stronger recovery confirmation, but this test does not authorize a new COST rule.","","INSUFFICIENT_EVIDENCE: The small executable samples do not establish robust transfer failure or support a production decision."]
    (LIB/"COST_RECOVERY_STRATEGY_FAMILY.md").write_text("\n".join(lines)+"\n",encoding="utf-8")
    comp="# Cross-Ticker Recovery Comparison\n\n## COST comparison\n\nCOST was evaluated with the pre-existing QQQ recovery definitions and no COST-specific tuning. The complete quantitative COST evidence is in `research_outputs/cost_frozen_recovery_transfer/COST_FROZEN_RECOVERY_TRANSFER_REPORT.json`.\n\n| Strategy | Classification | Evidence |\n|---|---|---|\n| Controlled Reset | INSUFFICIENT_SAMPLE | 1 executable completed trade |\n| Recovery Stabilization After Reset | INSUFFICIENT_SAMPLE | 2 executable completed trades |\n| SMA50 Reclaim After Weakness | INSUFFICIENT_SAMPLE | 4 executable completed trades |\n\n## Cross-ticker questions\n\n1. Controlled Reset transfer: `INSUFFICIENT_SAMPLE`.\n2. Recovery Stabilization transfer: `INSUFFICIENT_SAMPLE`.\n3. SMA50 Reclaim transfer: `INSUFFICIENT_SAMPLE`.\n4. COST cannot be classified as closer to broad-index or individual-stock behavior from four trades; `INSUFFICIENT_SAMPLE`.\n5. Healthy broader-trend recovery may be important, but this run does not test that incrementally.\n6. Structural recovery may be necessary after deeper weakness, but this run does not establish necessity.\n7. COST weakens neither nor strengthens the current thesis; it adds sparse, negative descriptive evidence and leaves the thesis unresolved.\n\n## Evidence classification\n\nFACT: The frozen predicates existed before the COST test and COST was not used for discovery or threshold tuning.\n\nOBSERVED_PATTERN: COST produced very sparse executable samples under the unchanged canonical selector and liquidity/credit gates; every completed trade in this run lost money.\n\nHYPOTHESIS: Broader-trend health and structural recovery may matter for COST, consistent with the existing cross-ticker recovery thesis, but this COST transfer run cannot distinguish those explanations.\n\nINSUFFICIENT_EVIDENCE: COST does not support a strong transfer classification from the available executable sample. Overall classification: `INSUFFICIENT_EVIDENCE`. No strategy promotion or production change is justified.\n"
    (LIB/"CROSS_TICKER_RECOVERY_COMPARISON.md").write_text(comp,encoding="utf-8")
    print(json.dumps({k:{"completed":v["metrics"]["completed_trades"],"pnl":v["metrics"]["total_pnl"]} for k,v in overall["strategies"].items()},indent=2))
if __name__=="__main__": main()
